[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Handle identity redirects
[[redirects]]
  from = "/.netlify/identity/confirm"
  to = "/admin/"
  status = 302

[[redirects]]
  from = "/.netlify/identity/recover"
  to = "/admin/"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
